-- MySQL Script generated by MySQL Workbench
-- Fri Nov 14 11:31:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema viajeros_peru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema viajeros_peru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viajeros_peru` DEFAULT CHARACTER SET utf8mb4 ;
USE `viajeros_peru` ;

-- -----------------------------------------------------
-- Table `viajeros_peru`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `rol` ENUM('viajero', 'anfitrion', 'administrador') NULL DEFAULT 'viajero',
  `estado` ENUM('activo', 'inactivo', 'pendiente', 'suspendido') NULL DEFAULT 'pendiente',
  `idioma_preferido` ENUM('es', 'en') NULL DEFAULT 'es',
  `zona_horaria` VARCHAR(50) NULL DEFAULT 'UTC',
  `visibilidad_perfil` ENUM('publico', 'solo_verificados', 'privado') NULL DEFAULT 'publico',
  `config_notificaciones` TEXT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`anuncios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `anfitrion_id` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `ubicacion` VARCHAR(255) NOT NULL,
  `latitud` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitud` DECIMAL(11,8) NULL DEFAULT NULL,
  `tipo_actividad` VARCHAR(100) NOT NULL,
  `duracion_minima` INT(11) NULL DEFAULT 1,
  `duracion_maxima` INT(11) NULL DEFAULT 30,
  `cupos_disponibles` INT(11) NULL DEFAULT 1,
  `requisitos` TEXT NULL DEFAULT NULL,
  `comodidades` TEXT NULL DEFAULT NULL,
  `estado` ENUM('activo', 'inactivo', 'completo') NULL DEFAULT 'activo',
  `fecha_publicacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `anfitrion_id` (`anfitrion_id` ASC) ,
  CONSTRAINT `anuncios_ibfk_1`
    FOREIGN KEY (`anfitrion_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`anuncio_imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`anuncio_imagenes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `anuncio_id` INT(11) NOT NULL,
  `url_imagen` VARCHAR(255) NOT NULL,
  `orden` INT(11) NULL DEFAULT 1,
  `fecha_subida` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `anuncio_id` (`anuncio_id` ASC) ,
  CONSTRAINT `anuncio_imagenes_ibfk_1`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `viajeros_peru`.`anuncios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`bloqueos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`bloqueos_usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_bloqueador_id` INT(11) NOT NULL,
  `usuario_bloqueado_id` INT(11) NOT NULL,
  `fecha_bloqueo` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bloqueo_unico` (`usuario_bloqueador_id` ASC, `usuario_bloqueado_id` ASC) ,
  INDEX `usuario_bloqueado_id` (`usuario_bloqueado_id` ASC) ,
  CONSTRAINT `fk_bloqueado_usuario`
    FOREIGN KEY (`usuario_bloqueado_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_bloqueador_usuario`
    FOREIGN KEY (`usuario_bloqueador_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`comunidad_publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`comunidad_publicaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `autor_id` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `contenido` TEXT NOT NULL,
  `tipo` ENUM('experiencia', 'pregunta', 'evento', 'consejo') NULL DEFAULT 'experiencia',
  `etiquetas` TEXT NULL DEFAULT NULL,
  `estado` ENUM('activo', 'eliminado', 'oculto') NULL DEFAULT 'activo',
  `fecha_publicacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `autor_id` (`autor_id` ASC) ,
  CONSTRAINT `fk_publicacion_autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`comunidad_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`comunidad_comentarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `publicacion_id` INT(11) NOT NULL,
  `autor_id` INT(11) NOT NULL,
  `contenido` TEXT NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `publicacion_id` (`publicacion_id` ASC) ,
  INDEX `autor_id` (`autor_id` ASC) ,
  CONSTRAINT `fk_comentario_autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_comentario_publicacion`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `viajeros_peru`.`comunidad_publicaciones` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`favoritos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `anuncio_id` INT(11) NULL DEFAULT NULL,
  `usuario_favorito_id` INT(11) NULL DEFAULT NULL,
  `tipo` ENUM('anuncio', 'perfil') NOT NULL,
  `fecha_agregado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `favorito_unico` (`usuario_id` ASC, `anuncio_id` ASC, `usuario_favorito_id` ASC) ,
  INDEX `anuncio_id` (`anuncio_id` ASC) ,
  INDEX `usuario_favorito_id` (`usuario_favorito_id` ASC) ,
  CONSTRAINT `fk_favorito_anuncio`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `viajeros_peru`.`anuncios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_favorito_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_favorito_usuario_favorito`
    FOREIGN KEY (`usuario_favorito_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`logs_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`logs_auditoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NULL DEFAULT NULL,
  `accion` VARCHAR(100) NOT NULL,
  `recurso` VARCHAR(100) NULL DEFAULT NULL,
  `recurso_id` INT(11) NULL DEFAULT NULL,
  `detalles` TEXT NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `usuario_id` (`usuario_id` ASC) ,
  INDEX `accion` (`accion` ASC) ,
  INDEX `fecha_creacion` (`fecha_creacion` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`mensajes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `remitente_id` INT(11) NOT NULL,
  `destinatario_id` INT(11) NOT NULL,
  `anuncio_id` INT(11) NULL DEFAULT NULL,
  `contenido` TEXT NOT NULL,
  `leido` TINYINT(1) NULL DEFAULT 0,
  `estado` ENUM('enviado', 'entregado', 'visto', 'eliminado') DEFAULT 'enviado',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `remitente_id` (`remitente_id` ASC) ,
  INDEX `destinatario_id` (`destinatario_id` ASC) ,
  INDEX `anuncio_id` (`anuncio_id` ASC) ,
  CONSTRAINT `mensajes_ibfk_1`
    FOREIGN KEY (`remitente_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `mensajes_ibfk_2`
    FOREIGN KEY (`destinatario_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `mensajes_ibfk_3`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `viajeros_peru`.`anuncios` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`notificaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `tipo` ENUM('mensaje', 'solicitud', 'reserva', 'resena', 'sistema') NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `contenido` TEXT NOT NULL,
  `enlace` VARCHAR(255) NULL DEFAULT NULL,
  `leido` TINYINT(1) NULL DEFAULT 0,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `usuario_id` (`usuario_id` ASC) ,
  INDEX `leido` (`leido` ASC) ,
  CONSTRAINT `fk_notificacion_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`perfiles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `biografia` TEXT NULL DEFAULT NULL,
  `habilidades` TEXT NULL DEFAULT NULL,
  `idiomas` VARCHAR(255) NULL DEFAULT NULL,
  `foto_perfil` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(255) NULL DEFAULT NULL,
  `intereses` TEXT NULL DEFAULT NULL,
  `experiencias_previas` TEXT NULL DEFAULT NULL,
  `redes_sociales` TEXT NULL DEFAULT NULL,
  `disponibilidad` VARCHAR(50) NULL DEFAULT NULL,
  `estado_verificacion` ENUM('no_verificado', 'pendiente', 'verificado') NULL DEFAULT 'no_verificado',
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_id` (`usuario_id` ASC) ,
  CONSTRAINT `perfiles_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`reportes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_reportador_id` INT(11) NOT NULL,
  `usuario_reportado_id` INT(11) NULL DEFAULT NULL,
  `anuncio_reportado_id` INT(11) NULL DEFAULT NULL,
  `publicacion_reportada_id` INT(11) NULL DEFAULT NULL,
  `tipo` ENUM('usuario', 'anuncio', 'publicacion', 'mensaje') NOT NULL,
  `motivo` TEXT NOT NULL,
  `estado` ENUM('pendiente', 'revisado', 'resuelto') NULL DEFAULT 'pendiente',
  `fecha_reporte` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `usuario_reportador_id` (`usuario_reportador_id` ASC) ,
  INDEX `usuario_reportado_id` (`usuario_reportado_id` ASC) ,
  INDEX `anuncio_reportado_id` (`anuncio_reportado_id` ASC) ,
  INDEX `publicacion_reportada_id` (`publicacion_reportada_id` ASC) ,
  CONSTRAINT `fk_reporte_anuncio`
    FOREIGN KEY (`anuncio_reportado_id`)
    REFERENCES `viajeros_peru`.`anuncios` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_reporte_publicacion`
    FOREIGN KEY (`publicacion_reportada_id`)
    REFERENCES `viajeros_peru`.`comunidad_publicaciones` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_reporte_usuario_reportado`
    FOREIGN KEY (`usuario_reportado_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_reporte_usuario_reportador`
    FOREIGN KEY (`usuario_reportador_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`reservas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `anuncio_id` INT(11) NOT NULL,
  `viajero_id` INT(11) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` ENUM('pendiente', 'aceptada', 'rechazada', 'cancelada', 'completada') NULL DEFAULT 'pendiente',
  `mensaje_solicitud` TEXT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_respuesta` TIMESTAMP NULL DEFAULT NULL,
  `fecha_actualizacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `anuncio_id` (`anuncio_id` ASC) ,
  INDEX `viajero_id` (`viajero_id` ASC) ,
  CONSTRAINT `reservas_ibfk_1`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `viajeros_peru`.`anuncios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `reservas_ibfk_2`
    FOREIGN KEY (`viajero_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`resenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`resenas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `reserva_id` INT(11) NOT NULL,
  `autor_id` INT(11) NOT NULL,
  `destinatario_id` INT(11) NOT NULL,
  `puntuacion` TINYINT(4) NOT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reserva_autor_unico` (`reserva_id` ASC, `autor_id` ASC) ,
  INDEX `autor_id` (`autor_id` ASC) ,
  INDEX `destinatario_id` (`destinatario_id` ASC) ,
  CONSTRAINT `resenas_ibfk_1`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `viajeros_peru`.`reservas` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `resenas_ibfk_2`
    FOREIGN KEY (`autor_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `resenas_ibfk_3`
    FOREIGN KEY (`destinatario_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `viajeros_peru`.`verificaciones_identidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viajeros_peru`.`verificaciones_identidad` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `tipo_documento` ENUM('dni', 'pasaporte', 'carnet_extranjeria') NOT NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  `documento_archivo` VARCHAR(255) NOT NULL,
  `selfie_archivo` VARCHAR(255) NOT NULL,
  `estado` ENUM('pendiente', 'verificado', 'rechazado') NULL DEFAULT 'pendiente',
  `fecha_solicitud` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_revision` TIMESTAMP NULL DEFAULT NULL,
  `notas_admin` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_unico` (`tipo_documento` ASC, `numero_documento` ASC) ,
  INDEX `usuario_id` (`usuario_id` ASC) ,
  CONSTRAINT `fk_verificacion_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `viajeros_peru`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

USE `viajeros_peru`;

DELIMITER $$
USE `viajeros_peru`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `viajeros_peru`.`crear_perfil_automatico`
AFTER INSERT ON `viajeros_peru`.`usuarios`
FOR EACH ROW
BEGIN
    INSERT INTO `perfiles` (`usuario_id`) VALUES (NEW.id);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
